apiVersion: apps/v1
kind: Deployment
metadata:
  name: server1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server1
  template:
    metadata:
      labels:
        app: server1
    spec:
      containers:
      - name: server1
        image: server1-image:latest
        imagePullPolicy: Never  # Add this line
        ports:
        - containerPort: 5000
